src/index.ts
This pull request enables the dot character (`.`) to be present in a CSS class, such as in `m-0.5`.
It also adds a small performance improvement by ignoring numbers in SVG paths, which were previously being matched. That should reduce the amount of ignored items in memory.
At the moment existing Tailwind classes, such as `p-0.5` and `ml-1.5`, are being ignored.
As a result windicss does not generate the corresponding CSS for these classes.
=> [fix] Allow .5 utility classes from TailwindCSS

src/index.ts
Otherwise it errors in a VitePress project where `index.html` is served virtually.
=> fix: only search index.html if exists

example/src/App.vue, src/constants.ts, src/index.ts
This pull request fixes the scanner so that it can parse conditional CSS rules in Vue templates.
Checked on the example and in one of my projects, but since regexes are tricky and this one has had many iterations, would like @antfu to review it before merging.
Using ```[^"'`<>,]``` is a simple way to avoid all terminators, and any partial matches on HTML tags.
Using `+?` makes the match non-greedy, which means it will stop as soon as it finds the first opening `\1`.
=> fix: conditional CSS in Vue templates, close #7

packages/plugin-utils/src/regexes.ts
this enables selectors like:
2xl:text-xl
or
+lg:bg-red-900
=> fix: class check regex to accept variants starting with numbers and "+"

packages/plugin-utils/src/createUtils.ts, packages/plugin-utils/src/options.ts
This pull request adds `root` as a user option.
When provided, it takes precedence over Vite's config `root`.
When not provided, the behavior remains unchanged, so this can be released in a `patch` version.
In [projects](https://github.com/ElMassimo/pingcrm-vite) where Vite's root is not the project root, it can be preferable for files and dirs provided in the configuration options to be [resolved](https://github.com/ElMassimo/pingcrm-vite/blob/main/vite.config.ts#L16-L19) against the project root instead of Vite's root.
Files and dirs needed to be resolved manually:
```js
const resolve = (file) => path.resolve(process.cwd(), file)
export default defineConfig({
plugins: [
WindiCSS({
config: resolve('windi.config.ts'),
scan: {
dirs: ['app/views', 'app/helpers', …
```
=> feat: Allow users to provide a custom root to resolve files against

examples/vue-pug/src/App.vue, examples/vue-pug/src/InvalidPug.vue, packages/plugin-utils/src/transformers/pug.ts
Previously if there was invalid pug code, the exception would be pushed up to the compiler when windy is initialised. For the windi init to handle this exception is a bit redundant as the rest of the build process will also pick them up. 
Instead, we can just ignore invalid pug files and let them bubble up elsewhere. This is similar to how runtime component imports work.
=> fix(pug): invalid pug breaking builds

packages/vite-plugin-windicss/package.json, packages/vite-plugin-windicss/src/devtools.ts, pnpm-lock.yaml
Fix #95
When body-parser is used globally, Vite proxy post request will be invalid. So the body-parser plug-in is removed, and the parameters in the body are obtained manually
=> fix: ensure that the post request is successful

packages/plugin-utils/src/createUtils.ts, packages/vite-plugin-windicss/src/index.ts
This pull request adds the scanned files to Vite's dev server watcher, allowing changes to these files to trigger a re-evaluation of the Windi CSS styles.
This enables the plugin to detect new Windi CSS classes when making changes to server-side templates.
To minimize the impact of this feature, only matching files at startup will be watched. In order to detect added files, a user should manually enable globbing in Vite's file watcher:
```js
server: {
watch: {
disableGlobbing: false,
},
},
```
When using Vite in combination with a backend server, where some of the templates are rendered server-side, a typical configuration might look like:
```js
WindiCSS({
root: process.cwd(),
scan: {
fileExtensions: ['erb', 'html', 'vue', 'rb', 'jsx', 'tsx'],
dirs: ['app/views'],
},
}),
``` 
Any styles …
=> feat: Allow re-scanning files after changes by watching them in Vite.

packages/plugin-utils/src/createUtils.ts, packages/plugin-utils/src/options.ts, packages/plugin-utils/test/hooks.test.ts
Related to: https://github.com/windicss/nuxt-windicss-module/issues/30
We need an easy way for the end-user to hook into the option & configs. 
For this to work in the nuxt repo I'll probably have to setup hooks to wrap these as the nuxt context is required to resolve the config properly.
=> feat(hooks): add onOptionsResolved & onConfigResolved hooks

packages/plugin-utils/src/resolveOptions.ts
inspiration of taken node fs,
I need a non promise version for preprocessor, so i suggest adding a sync function, so plugins can choose which to use
since pre-processor in svelte itself can't be async, just files parsing. and do not want to load config for each file over and over again.
hope you get the idea and can either merge or improve on it
EDIT: removed the hook into config, since that was the only async thing
=> feat: add loadConfigurationSync

packages/plugin-utils/src/createUtils.ts, test/__snapshots__/transform.test.ts.snap, test/transform.test.ts
When you have scoped styles within Vue, and you use windi animations as:
```
.pulse-class {
@apply relative w-40 h-40 rounded-full bg-teal-600 opacity-80 animate-pulse;
}
```
It will add the keyframe to the transformed css. This leads to duplicates and another vue specific issue around the scope ids and not transforming the keyframes.
Fixes https://github.com/windicss/windicss/issues/212
=> feat: Globalise keyframes

packages/plugin-utils/src/createUtils.ts
We added it as a scan target but we aren't transforming it at the moment, this fixes that.
Identified it as the issue when debugging this issue https://github.com/windicss/nuxt-windicss-module/issues/95
=> fix: support pcss as a CSS transform target

packages/vite-plugin-windicss/src/index.ts
as suggested by [rollup](https://rollupjs.org/guide/en/#direct-plugin-communication), vite-plugin-svelte moved the location it searches for additional preprocessors to the api namespace:
see https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/CHANGELOG.md
This PR updates vite-plugin-windicss to use it.
=> feat: move sveltePreprocess to api namespace

packages/plugin-utils/src/resolveOptions.ts
This pull request ensures that when users provide the `root` option, it's used consistently when loading configuration files.
The `root` user option was [introduced for projects where Vite's root does not match the project root](https://github.com/windicss/vite-plugin-windicss/blob/8b739620b651b5c0e043165e04d266e973be2b2c/packages/plugin-utils/src/createUtils.ts#L28), allowing files to be resolved correctly.
When the `windi.config.ts` file was introduced, files [were correctly resolved using the user provided root](https://github.com/windicss/vite-plugin-windicss/pull/110/files#diff-7cce94c31d7e1a4a6328850ea2b8a8a01a9053ccbbb07bd67617ecebec403befR55-R60).
In #129, the precedence was accidentally inverted when loading configuration files, which means configuration files would be resolved …
=> fix: Ensure the root option provided by the user has higher priority (close #214)

packages/rollup-plugin-windicss/src/index.ts
Previously if the user didn't set the `transformCSS` option explicitly then it would be disabled since `undefined == null`. However, [it should be enabled by default](https://github.com/windicss/vite-plugin-windicss/blob/v1.3.0/packages/plugin-utils/src/options.ts#L157-L162) so this behaviour is incorrect. I have changed it to perform the same check as in `transformGroups` whereby it is enabled unless explicitly set to `false`.
=> fix(rollup): respect default for `transformCSS` option in Rollup plugin

packages/config/package.json, packages/config/src/index.ts, pnpm-lock.yaml
close #233 
jiti updates: https://github.com/unjs/jiti/pull/39
Related to: https://github.com/windicss/windicss-webpack-plugin/issues/93
=> fix: disable jiti v8cache

packages/vite-plugin-windicss/package.json
- fixes WindiCSS is not a function when type module is set in
package.json, also fixes TypeScript import errors for other workarounds
suggested in #90. Code from
https://github.com/windicss/vite-plugin-windicss/issues/90#issuecomment-891747631
=> fix: add `exports` field, resolve #90

packages/vite-plugin-windicss/src/devtools.ts
Fixes #241: By addressing reference to deprecated global variable __dirname as per node's [recommendation](https://nodejs.org/api/esm.html#esm_no_filename_or_dirname).
While the `lint`, `test` and `build` command ran fine after these changes. `test:examples` blew up. Not sure why. It does not seem to be due to the changes created by this PR.
=> fix(vite): makes devtools esm compatible, close #241

packages/plugin-utils/src/regexes.ts, test/regex.test.ts
fix mismatch includes '+()'.
Eg:
```html
<div class="h-[calc(var(--box-size)+20rem)]">Hello</div>
```
=> fix: mismatch includes '+()'

packages/plugin-utils/src/regexes.ts
Should fix https://github.com/windicss/vite-plugin-windicss/issues/256
Simply changed `regexAttributifyItem` to detect the attributes even when there's a space between `key` and `value` like: `h = "20"`. Did this by adding optional whitespace matching before and after the `=` using `\s?=\s?`.
=> fix: support for whitespace in attribute/value pair

packages/plugin-utils/src/regexes.ts
The vertically-aligned attributes
```
bg     = "blue-400 hover:blue-500 dark:blue-500 dark:hover:blue-600"
text   = "sm white"
font   = "mono light"
p      = "y-2 x-4"
border = "2 rounded blue-200"
```
are much more readable vs the non-vertically-aligned
```
bg="blue-400 hover:blue-500 dark:blue-500 dark:hover:blue-600"
text="sm white"
font="mono light"
p="y-2 x-4"
border="2 rounded blue-200"
```
fix #256
=> fix: support multiple whitespace in attribute/value pair

packages/shared/virtual-module.ts
resolves https://github.com/windicss/nuxt-windicss/issues/180
context: https://github.com/nuxt/framework/issues/7372
=> fix: allow matching virtual id with query parameters

packages/plugin-utils/src/createUtils.ts
Both `isIncluded` and `isExcluded` contains perform `slash` function
=> perf: remove excess code

tsconfig.json
An error occurs using Vite4 pnpm dev
`tsup`从`v6.4.0`开始默认从`tsconfig.json`读取配置，因为现在`target`的配置为`es2017`，所以导致`import.meta`不支持，打包会生成`import_meta.url`
=> fix: The "path" argument must be of type string or an instance of URL. Received undefined

packages/vite-plugin-windicss/package.json
This fixes this typescript error, when one tries to `import windiCSS from 'vite-plugin-windicss';`: 
```
Could not find a declaration file for module 'vite-plugin-windicss'. 
'/project/node_modules/vite-plugin-windicss/dist/index.mjs' implicitly has an 'any' type.
There are types at '/project/node_modules/vite-plugin-windicss/dist/index.d.ts', but this 
result could not be resolved when respecting package.json "exports". 
The 'vite-plugin-windicss' library may need to update its package.json or typings.ts(7016)
```
This happens with vite-plugin-windicss v1.9.0, typescript v5.1.6 and the `moduleResolution` tsconfig compiler-option set to `bundler`, which per my understanding makes typescript import stuff only from what's defined in a module's `exports`.
=> fix: include types in package.json `exports`

packages/config/src/index.ts
Along with https://github.com/unjs/jiti/pull/112 this allows us to use `.mts` files for configuring windicss. 
This fixes a problem where I needed to import from a ESM-only library in my `windi.config.js`.
=> feat: search for *.config.mts as config file

packages/shared/virtual-module.ts, packages/vite-plugin-windicss/package.json, packages/vite-plugin-windicss/src/index.ts
In vite5, `watchChange` is triggered before `hmr` even if the `devServer` is started, which causes the hot update to fail, add the `inHmr` flag to skip the repeat trigger (as in vite4)
I simply tested vite4 and vite5 in the local area, and now their HMR works well.
If there is any case, I was ignored, please tell me. 🤣
Maybe there are stricter restrictions here, even specific to the vite version
=> fix(vite-plugin-windicss): fix vite5 hmr
